datagrabber:
  AutoGrabbing: true
  RefreshRate: 3
  SavePath: /home/thomas/ropose/new_colropose/ropose_data
  SimCamLookAtRange: 2.0
  SimCamLookAtYRange: -1.0
  SimCamMaxAzimuthalAng: 0.0
  SimCamMaxPolarAng: 3.1415927410125732
  SimCamMaxRadius: 8.0
  SimCamMinAzimuthalAng: 6.2831854820251465
  SimCamMinPolarAng: 0.3141592741012573
  SimCamMinRadius: 2.0
  SwitchCamPoses: false

  Cameras:
  - name: "depthcam1"
    linkName: "depthcam1_link"
    frames: ["rgb"]
    frameLinks: ["depthcam1_color_optical_frame"]
    isOpticalFrame: [true]
    frameTopics: ["/depthcam1/depthcam1/color/image_raw"]
    camInfoTopics: ["/depthcam1/depthcam1/color/camera_info"]
    
  TransformNames: [
    "base_link",
    "shoulder_link",
    "upper_arm_link",
    "forearm_link",
    "wrist_1_link",
    "wrist_2_link",
    "wrist_3_link"
  ]